RCPS:183-188-desktop-backend-maintenance-Refactor-Offense
RoCS2024/osd-records-mgt-desktop-app pull request #13
Opened 2024-11-19 18:10 UTC by Joven2002

This request includes all desktop backend maintenance for refactoring offense. The code on this request has refactored accordingly to the coding standards. All unnecessary code has removed. And also The functionalities are completely working and there are no bugs that causes by refactoring.

2024-11-20 11:10 UTC, JustineDaveMagnaye approved these changes

2024-11-20 11:18 UTC, zhairanicolepacheco approved these changes

2024-11-20 14:33 UTC, esdi-00 commented on src/main/java/com/rc/porms/appl/facade/user/impl/UserFacadeImpl.java
> +import java.util.List;
where did you use this LIst?

2024-11-20 14:34 UTC, esdi-00 commented on src/main/java/com/rc/porms/data/user/dao/UserDao.java
> +import java.util.List;
List?

2024-11-20 14:35 UTC, esdi-00 commented on src/main/java/com/rc/porms/data/utils/user/QueryConstant.java
> +
empty lines?

2024-11-20 14:36 UTC, esdi-00 commented on src/main/java/com/rc/porms/appl/facade/user/UserFacade.java
> +import java.util.List;
unused imports

2024-11-20 14:36 UTC, esdi-00 requested changes
see comments

2024-11-23 06:14 UTC, esdi-00 approved these changes

2024-11-23 08:12 UTC, merged