RCPS-66 desktop-frontend-maintenance: Refactor Login Module
RoCS2024/osd-records-mgt-desktop-app pull request #8
Opened 2024-10-15 06:36 UTC by Conconrad

ACCEPTANCE CRITERIA:

The code should be refactored based on the coding standards.

All unnecessary codes must be removed.

The system’s functionality must be working even after refactoring.

There should be no bugs brought by the refactoring.

2024-10-15 11:24 UTC, zhairanicolepacheco requested changes
.idea folder is included in the commit, please add .idea/ to the .gitignore file to prevent it from being tracked

2024-10-15 11:27 UTC, zhairanicolepacheco requested changes
do not commit the modal component as we refactor changes per function, comment out or remove it's usage in the login module

2024-10-18 12:35 UTC, esdi-00 commented on porms-ums-application/src/main/java/com/system/demo/appl/facade/user/impl/UserFacadeImpl.java
> +     * The logger for this class.
logger?

2024-10-18 12:36 UTC, esdi-00 commented on porms-ums-application/src/main/java/com/system/demo/UserInfoMgtApplication.java
> +public class UserInfoMgtApplication {
missing javadocs

2024-10-18 12:38 UTC, esdi-00 commented on porms-ums-application/src/main/java/com/system/demo/data/connection/ConnectionHelper.java
> +    public static String username = "system";
incorrect user

2024-10-18 12:40 UTC, esdi-00 requested changes
provide all the necessary documentations
check other comments

2024-10-21 12:24 UTC, esdi-00 requested changes
why is the repo inside another folder porms-ums-application?
why check in .idea codes?
still missing some javadocs

2024-11-11 13:23 UTC, closed without merging